# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Updated_at',
            new_name='updated_at',
        ),
    ]
